def reset_models():
    mod_blockrnn.reset_model()
    mod_blocklstm.reset_model()
    mod_blockgru.reset_model()
    mod_nbeats.reset_model()
    mod_nhits.reset_model()
    mod_tcn.reset_model()
    mod_dlinear.reset_model()
    mod_nlinear.reset_model()
    mod_tide.reset_model()
    mod_tsmixer.reset_model()

    mod_blockrnn_multi.reset_model()
    mod_blocklstm_multi.reset_model()
    mod_blockgru_multi.reset_model()
    mod_nbeats_multi.reset_model()
    mod_nhits_multi.reset_model()
    mod_tcn_multi.reset_model()
    mod_dlinear_multi.reset_model()
    mod_nlinear_multi.reset_model()
    mod_tide_multi.reset_model()
    mod_tsmixer_multi.reset_model()
